version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App_Final"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: "MySQL_Database_Tree"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro